name: Add Labels

on:
  pull_request:
    types: [opened]

jobs:
  pull_request_created:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 'Build Pending'
